# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b20ef585b76784e43f1e37b74341faf4438c22b9b17abb9f7eb8c7150281cd221a8e7227790601fc8b9cccef0b25e1f7d87ed3dec1b2fc5dfef4e6f1c34ddbe9

test:
  secret_key_base: def495d43e922763d3bec22eb9817d64233354cd5feb45dc093e073484df7483b6343b23b5a64d62e44445d169858a87e641150287c5391768705e3cd40b59c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
